name: "Build and push binaries to cachix"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - name: Setup cachix action
        uses: cachix/cachix-action@v14
        with:
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          name: polkadot
      - name: Nix flake check
        run: nix flake check
      - name: Nix flake develop
        run: nix develop
