name: "Build and publish to Cachix and FlakeHub ❄️"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Free disk space
        run: curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          name: polkadot
      - name: Nix flake check
        run: nix flake check -L --max-jobs 1 --option cores 1
      - name: Nix flake develop
        run: nix develop
      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          name: "andresilva/polkadot.nix"
          rolling: true
          visibility: public
