name: "Build and publish to Cachix and FlakeHub ❄️"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Delete unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          name: polkadot
      - name: Nix flake check
        run: nix flake check --max-jobs 1
      - name: Nix flake develop
        run: nix develop
      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          name: "andresilva/polkadot.nix"
          rolling: true
          visibility: public
